In [1]:
import numpy as np

In [2]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [ ]:
# create list

In [5]:
mylist=[0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [6]:
type(mylist)

list

In [ ]:
converting list to numpy

In [7]:
arr=np.array(mylist)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
np.arange(10,20)

NameError: name 'np' is not defined

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [14]:
np.arange(10,30,30,3)

TypeError: Cannot interpret '3' as a data type

In [15]:
np.arange(20,8)

array([], dtype=int32)

In [16]:
np.arange(-20,8)#1st arg should be less then 2nd arg

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [17]:
n=np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [21]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,2,))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [29]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
np.three(3)

AttributeError: module 'numpy' has no attribute 'three'

In [2]:
rand(3,2)

NameError: name 'rand' is not defined

In [3]:
random.rand(2)

NameError: name 'random' is not defined

In [4]:
np.random.rand(2)

NameError: name 'np' is not defined

In [5]:
np.random.rand(2)

NameError: name 'np' is not defined

In [6]:
import numpy as np


In [7]:
np.random.rand(2)

array([0.0964613 , 0.55094217])

In [8]:
np.random.rand(3)

array([0.18765247, 0.32529751, 0.95826423])

In [9]:
np.random.rand(3,2)

array([[0.62203895, 0.43329121],
       [0.85711377, 0.50437448],
       [0.41466471, 0.95331497]])

In [18]:
np.random.randint(3)

0

In [22]:
np.random.randint(2,10)

5

In [25]:
np.random.randint(2,10,4)

array([5, 9, 5, 9])

In [26]:
np.random.randint(-2,10,4)

array([-1,  6, -1,  4])

np.random.randint(10,40,(10,10))

In [30]:
m=np.random.randint(10,40,(10,10))
m

array([[14, 27, 12, 39, 36, 31, 10, 31, 21, 16],
       [16, 14, 17, 23, 21, 13, 35, 22, 31, 10],
       [15, 16, 39, 37, 38, 26, 25, 14, 12, 11],
       [31, 13, 29, 18, 37, 17, 33, 18, 27, 11],
       [24, 29, 18, 28, 35, 10, 30, 15, 15, 27],
       [19, 34, 10, 20, 34, 26, 23, 19, 21, 31],
       [22, 24, 14, 35, 28, 38, 19, 11, 26, 32],
       [15, 32, 16, 36, 24, 10, 38, 37, 32, 31],
       [28, 18, 19, 37, 11, 35, 25, 33, 10, 26],
       [31, 39, 37, 36, 36, 23, 39, 14, 27, 17]])

NameError: name 'arr' is not defined

In [33]:
arr=np.array(mylist)
arr

NameError: name 'mylist' is not defined

In [34]:
arr.reshape(1,6)

NameError: name 'arr' is not defined

In [35]:
m

array([[14, 27, 12, 39, 36, 31, 10, 31, 21, 16],
       [16, 14, 17, 23, 21, 13, 35, 22, 31, 10],
       [15, 16, 39, 37, 38, 26, 25, 14, 12, 11],
       [31, 13, 29, 18, 37, 17, 33, 18, 27, 11],
       [24, 29, 18, 28, 35, 10, 30, 15, 15, 27],
       [19, 34, 10, 20, 34, 26, 23, 19, 21, 31],
       [22, 24, 14, 35, 28, 38, 19, 11, 26, 32],
       [15, 32, 16, 36, 24, 10, 38, 37, 32, 31],
       [28, 18, 19, 37, 11, 35, 25, 33, 10, 26],
       [31, 39, 37, 36, 36, 23, 39, 14, 27, 17]])

In [37]:
b=np.random.randint(10,20,(5,4))
b

array([[18, 16, 10, 10],
       [17, 13, 10, 16],
       [12, 19, 15, 12],
       [15, 19, 15, 12],
       [16, 10, 14, 18]])

In [38]:
b[:]

array([[18, 16, 10, 10],
       [17, 13, 10, 16],
       [12, 19, 15, 12],
       [15, 19, 15, 12],
       [16, 10, 14, 18]])

In [39]:
b[1:4]

array([[17, 13, 10, 16],
       [12, 19, 15, 12],
       [15, 19, 15, 12]])

In [40]:
b

array([[18, 16, 10, 10],
       [17, 13, 10, 16],
       [12, 19, 15, 12],
       [15, 19, 15, 12],
       [16, 10, 14, 18]])

In [41]:
b[-1:]

array([[16, 10, 14, 18]])

In [42]:
b[:-1]

array([[18, 16, 10, 10],
       [17, 13, 10, 16],
       [12, 19, 15, 12],
       [15, 19, 15, 12]])